### ISSUE TITLE
Add CentOS 6 support

### ISSUE THREAD

**Issue by arm4b** [StackStorm/chef-stackstorm#18]
StackStorm works on `CentOS 6`, there are instructions: https://docs.stackstorm.com/install/rhel6.html

It's probably low priority to verify if cookbook requires any changes to work with CentOS 6 + `kitchen.yml`.

**Comment by shortdudey123** [comment]
Was already working on a PR for this over the weekend actually :)

**Comment by arm4b** [comment]
Awesome!

**Comment by shortdudey123** [comment]
Looks like this actually will not work without some tweeking on the stackstorm cookbook side.  The rabbitmq cookbook does not support centos 6 since the version it installs requires a newer version of erlang than is in the el6 repo's.

```
       Recipe: rabbitmq::default
         * yum_package[socat] action install
           - install version 1.7.2.3-1.el6 of package socat
         * remote_file[/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm] action create_if_missing
           - create new file /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm
           - update content in file /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm from none to b68895
           (new content is binary, diff output suppressed)
           - restore selinux security context
         * rpm_package[/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm] action install

           ================================================================================
           Error executing action `install` on resource 'rpm_package[/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm ----
           STDOUT: 
           STDERR: warning: /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 056e8e56: NOKEY
           error: Failed dependencies:
            erlang >= R16B-03 is needed by rabbitmq-server-3.6.1-1.noarch
           ---- End output of rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm ----
           Ran rpm  -i /tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb

           121:     rpm_package "#{Chef::Config[:file_cache_path]}/#{node['rabbitmq']['rpm_package']}"
           122:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb:121:in `from_file'

           rpm_package("/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm") do
             package_name "/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :rpm_package
             cookbook_name "rabbitmq"
             recipe_name "default"
             source "/tmp/kitchen/cache/rabbitmq-server-3.6.1-1.noarch.rpm"
             version "3.6.1-1"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by arm4b** [comment]
> The rabbitmq cookbook does not support centos 6 since the version it installs requires a newer version of erlang than is in the el6 repo's.

Wasn't expecting something friendly from anything related to `EL6` :smile:

**Comment by shortdudey123** [comment]
> Wasn't expecting something friendly from anything related to EL6 😄

true story

**Comment by shortdudey123** [comment]
@armab do we still want this considering it will take some customization to get it to work?
personally, i would say its probably not worth it

**Comment by arm4b** [comment]
@shortdudey123 Yeah, I agree with you.

Let's just keep this Issue for informational purposes.
If someone needs `CentOS6` / `RHEL6`, we're open to PR contribution :)

**Comment by shortdudey123** [comment]
cool, going to close for now then

**Comment by arm4b** [comment]
I mean, let's keep it open for Informational purposes :)
Eg. it's a good thing to add, but doesn't look like a big priority or significance for now.
